### ISSUE TITLE
Error starting addon

### ISSUE THREAD

**Issue by vincentkoevoets** [kdw2060/hassio-addons#51]
Well this looks promising! Unbelievable that there is no way to get future events with the native HA calendar configuration. 
I tried this addon, but I get the following error when starting it:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Hass Calendar Addon
 Addon to consume caldav and google calendars and make calendar events available as sensordata in Home Assistant.
-----------------------------------------------------------
 Add-on version: 0.302
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (amd64 / qemux86-64)
 Home Assistant Core: 2023.7.3
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
added 81 packages, and audited 82 packages in 9s
24 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 9.1.2 -> 9.8.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
npm notice Run `npm install -g npm@9.8.1` to update!
npm notice 
System locale: en-US
Luxon locale set to: en-US
System timeZone: Europe/Amsterdam
/node_modules/node-cron/src/convert-expression/month-names-conversion.js:10
            expression = expression.replace(new RegExp(items[i], 'gi'), parseInt(i, 10) + 1);
                                    ^
TypeError: Cannot read properties of undefined (reading 'replace')
    at convertMonthName (/node_modules/node-cron/src/convert-expression/month-names-conversion.js:10:37)
    at interprete (/node_modules/node-cron/src/convert-expression/month-names-conversion.js:16:27)
    at interprete (/node_modules/node-cron/src/convert-expression/index.js:54:26)
    at validate (/node_modules/node-cron/src/pattern-validation.js:117:32)
    at new TimeMatcher (/node_modules/node-cron/src/time-matcher.js:14:9)
    at new Scheduler (/node_modules/node-cron/src/scheduler.js:9:28)
    at new ScheduledTask (/node_modules/node-cron/src/scheduled-task.js:22:27)
    at createTask (/node_modules/node-cron/src/node-cron.js:36:12)
    at Object.schedule (/node_modules/node-cron/src/node-cron.js:25:18)
    at Object.<anonymous> (/index.js:557:6)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
And this is my config (Radicale server):
```
locale: nl-NL
timeZone: ""
fetchDays: 10
fetchDaysPast: 0
fetchCRON: "3"
calendarList:
  - calName: Verjaardagen
    calType: caldav
    username: <username>
    password: <password>
    caldavUrl: https://<domain>:<port>/<username>/verjaardagen/
```

I have no clue what could be wrong here. I tried waiting it out like mentioned in the docs, but then I found out that the addon stops immediately after starting (as mentioned in the log). Can you help me?

Edit
After looking at the logs for Radicale and Nginx (reverse proxy), it seems that the addon never reaches Radicale server.

**Comment by kdw2060** [comment]
If you look carefully at the logs you can see the error happens when the node-cron module is used.
Your ```fetchCRON``` config is wrong, "3" is not a valid CRON format. Use the default CRON schedule or use a website that helps you create a valid CRON schedule (I link to one in the docs).

Btw, since Home Assistant 2023.07 Home Assistant can actually provide this data via a service call as well. I haven't got round to testing that. I'll make up my mind about maintaining this addon when I've had the time to evaluate the functionalities of the inbuilt service.

**Comment by vincentkoevoets** [comment]
Wow, I feel stupid now. The name of the field should have been a huge sign of what to enter there. Sorry for the noobness here. 
Works perfectly now. 

I tried to use the inbuilt service as well, but this was a pain in the a$$. I can call the calendar.list_events service, and it returns a huge list of events. But after that, there is no easy way to store, use or parse this data. Other than storing the data in a text file (python script via shell_command), parsing it (also via python) and fetch it again with a file sensor, which can then be read and formatted by a template sensor, I think the buildin service is pretty useless. 
Your addon does all this work by itself and returns a pretty list of events which is easily accessable. So thanks for the response and thanks for the addon!
